/*
 * This source file was generated by the Gradle 'init' task
 */
package thegame;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test 
    void windowCreationTest() {
        App app = new App();
        assertNotNull(app, "App instance should be created successfully");
    }
}
